spring:
  application:
    name: user-ms

  datasource:
    url: jdbc:postgresql://localhost:5432/user-ms
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
security:
  jwt:
    secretKey: "ashish12345678901234567890123456"
    expiration: 120000